### ISSUE TITLE
bug vacances toussaint 1990 zone C

### ISSUE THREAD

**Issue by pioc92** [AntoineAugusti/vacances-scolaires#11]
Bonjour,
j'ai checké les vacances de toussaint de l'année scolaire 1990/1991 et il n'y a pas à cette époque de zone C, uniquement deux zones A et B
Or le fichier data.csv indique des vacances scolaires pour la zone C du 27/10/1990 au 04/11/1990.
source :  https://cache.media.education.gouv.fr/file/85/3/5853.pdf

**Comment by AntoineAugusti** [comment]
Effectivement il n'y a pas de zone C à cette époque. Toutefois des tests sont présents pour vérifier que chaque zone a bien des vacances par zone et par année. Ceci demanderait un ajustement uniquement pour cette année.

Je choisis de ne pas m'en occuper pour le moment.
