### ISSUE TITLE
bug vacances été zone C 1992

### ISSUE THREAD

**Issue by pioc92** [AntoineAugusti/vacances-scolaires#12]
Bonjour, une autre issue trouvée concerne les vacances scolaires de l'été 1992
la zone C
Dans la source https://cache.media.education.gouv.fr/file/85/2/5852.pdf, les 3 zones reprennent les cours le 10/09/1992, or dans le fichier data, la zone C reprend le 07/09/1992

**Comment by AntoineAugusti** [comment]
Le lien est https://cache.media.education.gouv.fr/file/85/1/5851.pdf
