### ISSUE TITLE
2009 vacances hiver zone B

### ISSUE THREAD

**Issue by pioc92** [AntoineAugusti/vacances-scolaires#20]
Sur le ministère, c'est du 21/2 au 9/3, sur le fichier data, c'est du 22/2 au 9/3 
https://cache.media.education.gouv.fr/file/calendrier_scolaire/72/5/calendrier-scolaire-2008-2009_65725.pdf

J'ai fait une issue par coquille, dites-moi si je dois plutôt faire une issue avec toutes les erreurs si j'en trouve d'autres, merci

**Comment by AntoineAugusti** [comment]
Merci d'avoir ouvert toutes ces issues @pioc92 ! Une issue par erreur me convient tout à fait.

Si vous pouviez proposer des corrections par pull-request la prochaine fois, ce serait encore mieux 👍

**Comment by pioc92** [comment]
Ok. Merci pour le jeu de données en tout cas.
