### ISSUE TITLE
Impossible d'accéder au Vacances scolaire Zone B

### ISSUE THREAD

**Issue by funbben** [AntoineAugusti/vacances-scolaires#28]
Bonjour, 
J'ai bien ajouté dans mon Google Calendar les zones A et C, pour la B j'obtiens 
"Impossible d'ajouter cet agenda. Réessayez dans quelques minutes"
Lien utilisé : 
https://fr.ftp.opendatasoft.com/openscol/fr-en-calendrier-scolaire/Zone-B.ics

J'ai pu téléchargé le fichier en local.

Merci pour votre travail

**Comment by AntoineAugusti** [comment]
Bonjour,

Vous pouvez contacter le ministère de l'éducation qui est en charge de la diffusion de ces données : https://www.data.gouv.fr/fr/datasets/le-calendrier-scolaire/#/discussions.
