### ISSUE TITLE
bug pour les vacances de 1991/1992

### ISSUE THREAD

**Issue by pioc92** [AntoineAugusti/vacances-scolaires#7]
Je viens de récupérer le fichier data et j'ai pris au pif les données pour les vacances de février 1992 et je constate une erreur pour la zone A
Sur le site officiel de l'Education Nationale (http://cache.media.education.gouv.fr/file/85/1/5851.pdf), j'ai : 
**zone A :** Pour l’académie de Grenoble : Du vendredi [07-02-1992] au mardi [25-02-1992] Pour les autres académies : Du samedi [15-02-1992] au lundi [02-03-1992]  
**Zone B :** Du samedi [22-02-19921] au lundi [09-03-1992]
**Zone C:** Du samedi [29-02-19921] au lundi [16-03-1992] 

Or dans le fichier data.csv, j'ai respectivement : 
pour la zone A et B : du 22/02/1992 au 09/03/1992
pour la zone C: du 29/02/1992 au 16/03/1992 

La zone A pose problème car les vacances sont différentes pour l'académie de Grenoble. Peut-être faudrait-il prendre la valeur pour les autres académies de la zone?

**Comment by AntoineAugusti** [comment]
Bonjour,

Merci de votre vigilance. Je viens d'ouvrir une PR avec un correctif. @DavidDoukhan, tu sais ce qui a pu provoquer cette erreur ?
